authors:
  scriptsengineer:
    name: Rafael Correa        # Author name
    description: Programmer and Designer # Author description
    avatar: https://avatars.githubusercontent.com/u/1673249?s=400&u=200d0d74826f8597fe892012226d2948fc0050be&v=4         # Author avatar
    slug: Engenheiro           # Author profile slug
    url: https://github.com/scriptsengineer            # Author website URL